name: Browser extension CI

on:
    push:
        branches: ["**"]
        paths:
            - "browser-extension/**"
            - ".github/workflows/browser-extension-ci.yml"
    pull_request:
        branches: ["**"]
        paths:
            - "browser-extension/**"
            - ".github/workflows/browser-extension-ci.yml"

jobs:
    test:
        runs-on: ubuntu-latest

        strategy:
            matrix:
                node-version: [20.x, 22.x]
                # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

        defaults:
            run:
                working-directory: browser-extension

        steps:
            - uses: actions/checkout@v4
            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v4
              with:
                  node-version: ${{ matrix.node-version }}
            - run: npm test
